# Generated by Django 2.2.6 on 2020-11-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tagmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uom', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=124)),
                ('measured_property', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
