# Generated by Django 2.2.6 on 2021-04-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayfirst', models.BooleanField(default=True)),
                ('skiprows', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=124, null=True)),
                ('csvfile', models.FileField(upload_to='csvfiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Tagmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uom', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=124)),
                ('measured_property', models.CharField(blank=True, max_length=50, null=True)),
                ('csv_filename', models.CharField(max_length=124)),
                ('time_points', models.IntegerField(blank=True, null=True)),
                ('data_points', models.IntegerField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_upload.Batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='datafile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_upload.Datafile'),
        ),
    ]
