# Generated by Django 2.2.6 on 2021-04-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='tagsIdentified',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
