# Generated by Django 2.2 on 2020-12-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
