# Generated by Django 2.2.6 on 2021-04-13 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_batch_tagsidentified'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datafile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
