# Generated by Django 2.2 on 2020-12-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_auto_20201203_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='csv_filename',
            field=models.CharField(default='test', max_length=124),
            preserve_default=False,
        ),
    ]
