# Generated by Django 2.2 on 2020-12-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_tagmodel_csv_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmodel',
            name='name',
        ),
    ]
