# Generated by Django 2.2 on 2020-12-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_remove_tagmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(default='None', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
