# Generated by Django 2.2 on 2020-12-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0005_tagmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='date_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='time_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
