# Generated by Django 2.2 on 2020-12-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0006_auto_20201203_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmodel',
            name='date_points',
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='data_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
