# Generated by Django 2.2 on 2020-12-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0007_auto_20201203_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
