# Generated by Django 2.2.5 on 2021-03-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0008_auto_20201210_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=124)),
                ('csvfile', models.FileField(upload_to='csvfiles/')),
            ],
        ),
    ]
