# Generated by Django 2.2.5 on 2021-03-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0009_datafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='description',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
