# Generated by Django 2.2.6 on 2021-03-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0010_auto_20210304_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='status',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
